-- El administrador de demostración se crea con `npm run seed` dentro de backend.
-- La contraseña no se guarda en este archivo: se toma de SEED_ADMIN_PASSWORD.
-- Antes, aplica database/migrations/001_pmv1_inicial.sql en Supabase.
